### ISSUE TITLE
The url for accessing the github page link is broken

### ISSUE THREAD

**Issue by victormagalhaess** [chandrikadeb7/chandrikadeb7.github.io#3]
Hello, I was checking your README and when I tried clicking  at "chandrikadeb7.github.io" it was opening  "chandrikadeb7.gihub.io".(**gihub.io** instead of **github.io**).
This is just a typo when writing your url and easy to not see. 

Best regards, hope you're doing well

**Comment by chandrikadeb7** [comment]
@victormagalhaess Thanks!
