### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by salwinat0r** [chandrikadeb7/chandrikadeb7.github.io#9]
When I hit `npm-start` and open `localhost:8000`, the terminal shows me the following error

`ERROR`
`window is not defined`
`ReferenceError: window is not defined`
and a lot more information after that. 

I'm stuck with this. Would help me a great deal if you could reply to this.

**Comment by Mohendra-Murmu** [comment]
Same issue ⚠️
